# ENABLE:
#   - ACTION
#   - EDITORCONFIG
#   - REPOSITORY
#   - YAML

DISABLE:
  - C
  - CPP
  - LATEX
  - SPELL

DISABLE_ERRORS_LINTERS:
  - MAKEFILE_CHECKMAKE
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
