# ENABLE:
#   - ACTION
#   - EDITORCONFIG
#   - REPOSITORY
#   - YAML

DISABLE:
  - C
  - CPP
  - LATEX
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_GRYPE

DISABLE_ERRORS_LINTERS:
  - ACTION_ZIZMOR
  - MAKEFILE_CHECKMAKE
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS

ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
